name: Build Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Publish Release
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{secrets.GPG_KEY}}
          ORG_GRADLE_PROJECT_signingPassword: ${{secrets.GPG_PASSWORD}}
          ORG_GRADLE_PROJECT_repositoryUrl: 'https://s01.oss.sonatype.org/service/local/staging/deploy/maven2/'
          ORG_GRADLE_PROJECT_repositoryUsername: ${{secrets.REPO_USER}}
          ORG_GRADLE_PROJECT_repositoryPassword: ${{secrets.REPO_PASSWORD}}
        run: ./gradlew check publish